# Generated by Django 3.0 on 2019-12-23 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
